# Generated by Django 2.2.12 on 2020-05-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_gkjhgjhgkg"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="gkjhgjhgkg",),
    ]
