# Generated by Django 2.2.12 on 2020-05-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_customtext_gkjhgjhgkg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smhgfjgf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hguhyg', models.BigIntegerField()),
            ],
        ),
    ]
